export const maps = {
    "Altar of Flame": "https://bungie.net/img/destiny_content/pgcr/crucible_ness.jpg",
    "The Anomaly": "https://bungie.net/img/destiny_content/pgcr/crucible_the_anomaly.jpg",
    "Bannerfall": "https://bungie.net/img/destiny_content/pgcr/crucible_bannerfall.jpg",
    "The Burnout": "https://bungie.net/img/destiny_content/pgcr/pvp_the_burnout.jpg",
    "Cauldron": "https://bungie.net/img/destiny_content/pgcr/crucible_cauldron.jpg",
    "Convergence": "https://bungie.net/img/destiny_content/pgcr/pvp_longshot_2.jpg",
    "The Dead Cliffs": "https://bungie.net/img/destiny_content/pgcr/crucible_cliffside.jpg",
    "Distant Shore": "https://bungie.net/img/destiny_content/pgcr/crucible_distant_shore.jpg",
    "Endless Vale": "https://bungie.net/img/destiny_content/pgcr/crucible_grove.jpg",
    "Exodus Blue": "https://bungie.net/img/destiny_content/pgcr/crucible_exodus_blue.jpg",
    "The Fortress": "https://bungie.net/img/destiny_content/pgcr/crucible_hull.jpg",
    "Fragment": "https://bungie.net/img/destiny_content/pgcr/crucible_fragment.jpg",
    "Javelin-4": "https://bungie.net/img/destiny_content/pgcr/crucible_shaft.jpg",
    "Midtown": "https://bungie.net/img/destiny_content/pgcr/crucible_midtown.jpg",
    "Pacifica": "https://bungie.net/img/destiny_content/pgcr/pvp_pacifica.jpg",
    "Radiant Cliffs": "https://bungie.net/img/destiny_content/pgcr/pvp_radiant_cliffs.jpg",
    "Rusted Lands": "https://bungie.net/img/destiny_content/pgcr/crucible_rusted_lands.jpg",
    "Twilight Gap": "https://bungie.net/img/destiny_content/pgcr/crucible_twilight_gap.jpg",
    "Widow's Court": "https://bungie.net/img/destiny_content/pgcr/crucible_widows_court.jpg",
    "Wormhaven": "https://bungie.net/img/destiny_content/pgcr/pvp_wormhaven.jpg"
}
