export default {
    "Altar of Flame": "https://bungie.net/img/destiny_content/pgcr/crucible_ness.jpg",
    "The Anomaly": "https://bungie.net/img/destiny_content/pgcr/crucible_the_anomaly.jpg",
    "Bannerfall": "https://bungie.net/img/destiny_content/pgcr/crucible_bannerfall.jpg",
    "The Burnout": "https://bungie.net/img/destiny_content/pgcr/pvp_the_burnout.jpg",
    "Cauldron": "https://bungie.net/img/destiny_content/pgcr/crucible_cauldron.jpg",
    "The Citadel": "https://bungie.net/img/destiny_content/pgcr/pvp_peak.jpg",
    "Convergence": "https://bungie.net/img/destiny_content/pgcr/pvp_longshot_2.jpg",
    "The Dead Cliffs": "https://bungie.net/img/destiny_content/pgcr/crucible_cliffside.jpg",
    "Distant Shore": "https://bungie.net/img/destiny_content/pgcr/crucible_distant_shore.jpg",
    "Emperor's Respite": "https://bungie.net/img/destiny_content/pgcr/crucible_katana.jpg",
    "Endless Vale": "https://bungie.net/img/destiny_content/pgcr/crucible_grove.jpg",
    "Equinox": "https://bungie.net/img/destiny_content/pgcr/pvp_street.jpg",
    "Eternity": "https://bungie.net/img/destiny_content/pgcr/crucible_glaive.jpg",
    "Exodus Blue": "https://bungie.net/img/destiny_content/pgcr/crucible_exodus_blue.jpg",
    "Firebase Echo": "https://bungie.net/img/destiny_content/pgcr/pvp_echo.jpg",
    "The Fortress": "https://bungie.net/img/destiny_content/pgcr/crucible_hull.jpg",
    "Fragment": "https://bungie.net/img/destiny_content/pgcr/crucible_fragment.jpg",
    "Gambler's Ruin": "https://bungie.net/img/destiny_content/pgcr/crucible_gamblers_ruin.jpg",
    "Javelin-4": "https://bungie.net/img/destiny_content/pgcr/crucible_shaft.jpg",
    "Legion's Gulch": "https://bungie.net/img/destiny_content/pgcr/crucible_slag.jpg",
    "Meltdown": "https://bungie.net/img/destiny_content/pgcr/crucible_meltdown.jpg",
    "Midtown": "https://bungie.net/img/destiny_content/pgcr/crucible_midtown.jpg",
    "Pacifica": "https://bungie.net/img/destiny_content/pgcr/pvp_pacifica.jpg",
    "Radiant Cliffs": "https://bungie.net/img/destiny_content/pgcr/pvp_radiant_cliffs.jpg",
    "Retribution": "https://bungie.net/img/destiny_content/pgcr/crucible_elevator.jpg",
    "Rusted Lands": "https://bungie.net/img/destiny_content/pgcr/crucible_rusted_lands.jpg",
    "Solitude": "https://bungie.net/img/destiny_content/pgcr/crucible_solitude.jpg",
    "Twilight Gap": "https://bungie.net/img/destiny_content/pgcr/crucible_twilight_gap.jpg",
    "Vostok": "https://bungie.net/img/destiny_content/pgcr/crucible_observatory.jpg",
    "Widow's Court": "https://bungie.net/img/destiny_content/pgcr/crucible_widows_court.jpg",
    "Wormhaven": "https://bungie.net/img/destiny_content/pgcr/pvp_wormhaven.jpg"
}