name: Pages CI/CD
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: cd preload
      - run: npm install
      - run: node .
      - run: cd ../client
      - run: npm install
      - run: npm run build
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: client/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}
