name: Pages CI/CD
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set Up Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "14.x"
      - name: Preload Data
        working-directory: ./preload
        run: npm install && node .
      - name: Build Pages
        working-directory: ./client
        run: npm install && npm run build
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2.4.1
        with:
          target_branch: gh-pages
          build_dir: ./client/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_KEY: ${{ secrets.API_KEY }}
